Added support for Armbian w/ u-boot. That also required adding support for having /boot on the same partition as /

diff --git a/overctl b/overctl
--- a/overctl
+++ b/overctl
@@ -5,6 +5,8 @@ CMDLINE=cmdline.txt
 CMDLINE_RO=cmdline.txt.overlay
 CMDLINE_RW=cmdline.txt.orig
 
+UBOOTENV=armbianEnv.txt
+
 print_usage() {
 	cat <<-TEXT
 		Usage: ${0##*/} [-h|-r|-s|-t|-w]
@@ -23,9 +25,13 @@ print_usage() {
 cd $BOOT
 
 # Check that the files we need are present and readable
-for file in $CMDLINE $CMDLINE_RO $CMDLINE_RW; do
-	[ -r $file ] || { echo "ERROR: missing file $file" >&2 && exit 1; }
-done
+if [ -r $CMDLINE ]; then
+	for file in $CMDLINE $CMDLINE_RO $CMDLINE_RW; do
+		[ -r $file ] || { echo "ERROR: missing file $file" >&2 && exit 1; }
+	done
+elif ! [ -r $UBOOTENV ]; then
+	echo "ERROR: missing file $UBOOTENV" >&2 && exit 1
+fi
 
 # Process arg (if any)
 case "$1" in
@@ -42,18 +48,26 @@ case "$1" in
 			;;
 esac
 
-line_active=$(cat $CMDLINE)
-line_ro=$(cat $CMDLINE_RO)
-line_rw=$(cat $CMDLINE_RW)
+if [ -r "$CMDLINE" ]; then
+	line_active=$(cat $CMDLINE)
+	line_ro=$(cat $CMDLINE_RO)
+	line_rw=$(cat $CMDLINE_RW)
 
-# Check which CMDLINE is in use, this doubles as a sanity check
-if [ "$line_active" = "$line_ro" ]; then
-	state=RO
-elif [ "$line_active" = "$line_rw" ]; then
-	state=RW
+	# Check which CMDLINE is in use, this doubles as a sanity check
+	if [ "$line_active" = "$line_ro" ]; then
+		state=RO
+	elif [ "$line_active" = "$line_rw" ]; then
+		state=RW
+	else
+		echo "ERROR: $CMDLINE matches neither $CMDLINE_RO, nor $CMDLINE_RW" >&2
+		exit 1
+	fi
 else
-	echo "ERROR: $CMDLINE matches neither $CMDLINE_RO, nor $CMDLINE_RW" >&2
-	exit 1
+	if grep boot=overlay $UBOOTENV >/dev/null; then
+		state=RO
+	else
+		state=RW
+	fi
 fi
 
 check_permission() {
@@ -61,7 +75,9 @@ check_permission() {
 	[ $(id -u) -eq 0 ] || { echo "ERROR: requires root privileges" >&2; exit 1; }
 
 	# Check that we can write to CMDLINE, otherwise try to remount BOOT
-	if ! touch $CMDLINE 2>/dev/null; then
+	local cmdline=$CMDLINE
+	[ -r $CMDLINE ] || cmdline=$UBOOTENV
+	if ! touch $cmdline 2>/dev/null; then
 		mount -o remount,rw $BOOT 2>/dev/null
 		[ $? -eq 0 ] || { echo "ERROR: failed to mount $BOOT RW" >&2; exit 1; }
 		boot_remount=y
@@ -89,10 +105,27 @@ elif [ "$action" = "$state" ]; then
 	echo "/ is already set to be mounted $state on next boot" >&2
 	exit 1
 elif [ "$state" = "RO" ]; then
-	check_permission && cp $CMDLINE_RW $CMDLINE
+	check_permission && {
+		if [ -r "$CMDLINE" ]; then
+			cp $CMDLINE_RW $CMDLINE
+		else
+			sed -i '/^extraargs=/{s/boot=overlay//;s/  */ /g;s/ *$//};/^extraargs=$/d' $UBOOTENV
+		fi
+	}
 	newstate=RW
 elif [ "$state" = "RW" ]; then
-	check_permission && cp $CMDLINE_RO $CMDLINE
+	check_permission && {
+		if [ -r "$CMDLINE" ]; then
+			cp $CMDLINE_RO $CMDLINE
+		else
+			sed -i '/^extraargs=/{
+			          s/boot=overlay//g;s/  */ /g;s/=/&boot=overlay /;s/ *$//
+			          :1;N;b1
+			        }
+			        $a\
+extraargs=boot=overlay' $UBOOTENV
+		fi
+	}
 	newstate=RO
 fi
 
